services:
  - type: web
    name: bincom-election-explorer
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py migrate && python manage.py import_bincom_sql && python manage.py collectstatic --noinput
    startCommand: gunicorn config.wsgi:application
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
