services:
  - type: web
    name: bincom-election-explorer
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py migrate && python manage.py seed_demo_data --path bincom_test.sql && python manage.py collectstatic --noinput
    startCommand: gunicorn config.wsgi:application
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://bincom-election-explorer.onrender.com"
