# Generated by Django 5.2.12 on 2026-04-03 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncedLGAResult',
            fields=[
                ('result_id', models.AutoField(db_column='result_id', primary_key=True, serialize=False)),
                ('lga_name', models.CharField(db_column='lga_name', db_index=True, max_length=50)),
                ('party_abbreviation', models.CharField(db_column='party_abbreviation', max_length=4)),
                ('party_score', models.IntegerField(db_column='party_score')),
                ('entered_by_user', models.CharField(blank=True, db_column='entered_by_user', max_length=50)),
                ('date_entered', models.DateTimeField(blank=True, db_column='date_entered', null=True)),
                ('user_ip_address', models.CharField(blank=True, db_column='user_ip_address', max_length=50)),
            ],
            options={
                'db_table': 'announced_lga_results',
                'ordering': ['lga_name', 'party_abbreviation', 'result_id'],
            },
        ),
        migrations.CreateModel(
            name='AnnouncedPUResult',
            fields=[
                ('result_id', models.AutoField(db_column='result_id', primary_key=True, serialize=False)),
                ('polling_unit_uniqueid', models.CharField(db_column='polling_unit_uniqueid', db_index=True, max_length=50)),
                ('party_abbreviation', models.CharField(db_column='party_abbreviation', max_length=4)),
                ('party_score', models.IntegerField(db_column='party_score')),
                ('entered_by_user', models.CharField(blank=True, db_column='entered_by_user', max_length=50)),
                ('date_entered', models.DateTimeField(blank=True, db_column='date_entered', null=True)),
                ('user_ip_address', models.CharField(blank=True, db_column='user_ip_address', max_length=50)),
            ],
            options={
                'db_table': 'announced_pu_results',
                'ordering': ['polling_unit_uniqueid', 'party_abbreviation', 'result_id'],
            },
        ),
        migrations.CreateModel(
            name='LGA',
            fields=[
                ('uniqueid', models.AutoField(db_column='uniqueid', primary_key=True, serialize=False)),
                ('lga_id', models.IntegerField(db_column='lga_id', db_index=True)),
                ('lga_name', models.CharField(db_column='lga_name', max_length=50)),
                ('state_id', models.IntegerField(db_column='state_id', db_index=True)),
                ('lga_description', models.TextField(blank=True, db_column='lga_description', null=True)),
                ('entered_by_user', models.CharField(blank=True, db_column='entered_by_user', max_length=50)),
                ('date_entered', models.DateTimeField(blank=True, db_column='date_entered', null=True)),
                ('user_ip_address', models.CharField(blank=True, db_column='user_ip_address', max_length=50)),
            ],
            options={
                'db_table': 'lga',
                'ordering': ['lga_name'],
            },
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('partyid', models.CharField(db_column='partyid', max_length=11, unique=True)),
                ('partyname', models.CharField(db_column='partyname', max_length=11)),
            ],
            options={
                'db_table': 'party',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PollingUnit',
            fields=[
                ('uniqueid', models.AutoField(db_column='uniqueid', primary_key=True, serialize=False)),
                ('polling_unit_id', models.IntegerField(db_column='polling_unit_id')),
                ('ward_id', models.IntegerField(db_column='ward_id', db_index=True)),
                ('lga_id', models.IntegerField(db_column='lga_id', db_index=True)),
                ('uniquewardid', models.IntegerField(blank=True, db_column='uniquewardid', null=True)),
                ('polling_unit_number', models.CharField(blank=True, db_column='polling_unit_number', max_length=50, null=True)),
                ('polling_unit_name', models.CharField(blank=True, db_column='polling_unit_name', max_length=50, null=True)),
                ('polling_unit_description', models.TextField(blank=True, db_column='polling_unit_description', null=True)),
                ('lat', models.CharField(blank=True, db_column='lat', max_length=255, null=True)),
                ('long', models.CharField(blank=True, db_column='long', max_length=255, null=True)),
                ('entered_by_user', models.CharField(blank=True, db_column='entered_by_user', max_length=50, null=True)),
                ('date_entered', models.DateTimeField(blank=True, db_column='date_entered', null=True)),
                ('user_ip_address', models.CharField(blank=True, db_column='user_ip_address', max_length=50, null=True)),
            ],
            options={
                'db_table': 'polling_unit',
                'ordering': ['polling_unit_name', 'polling_unit_number', 'uniqueid'],
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('state_id', models.IntegerField(db_column='state_id', primary_key=True, serialize=False)),
                ('state_name', models.CharField(db_column='state_name', max_length=50)),
            ],
            options={
                'db_table': 'states',
                'ordering': ['state_name'],
            },
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('uniqueid', models.AutoField(db_column='uniqueid', primary_key=True, serialize=False)),
                ('ward_id', models.IntegerField(db_column='ward_id')),
                ('ward_name', models.CharField(db_column='ward_name', max_length=50)),
                ('lga_id', models.IntegerField(db_column='lga_id', db_index=True)),
                ('ward_description', models.TextField(blank=True, db_column='ward_description', null=True)),
                ('entered_by_user', models.CharField(blank=True, db_column='entered_by_user', max_length=50)),
                ('date_entered', models.DateTimeField(blank=True, db_column='date_entered', null=True)),
                ('user_ip_address', models.CharField(blank=True, db_column='user_ip_address', max_length=50)),
            ],
            options={
                'db_table': 'ward',
                'ordering': ['ward_name'],
            },
        ),
    ]
