# Generated by Django 5.2.12 on 2026-04-03 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SequenceCounter',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('next_value', models.PositiveIntegerField(default=1)),
            ],
            options={
                'db_table': 'sequence_counter',
            },
        ),
    ]
